.PHONY: all check clean

CPLUSPLUS?=g++
CPPFLAGS=-std=c++11 -Wall
LDFLAGS=-pthread

PWD=$(shell pwd)

all:
	echo "TODO(dkorolev): Add tests for bricks/file."

check:
	../scripts/check-headers.sh

build:
	mkdir -p $@

clean:
