#!/bin/bash

# Regenerates the C++ header containing the base64-encoded contents of `current.inl`.

OUT=current.inl.h

echo "// Generated by 'update_current_inl.sh'."> $OUT
echo >> $OUT
echo "#ifndef BRICKS_SYSTEM_CURRENT_INL_H" >> $OUT
echo "#define BRICKS_SYSTEM_CURRENT_INL_H" >> $OUT
echo >> $OUT
echo "#include <string>" >> $OUT
echo >> $OUT
echo "#include \"../util/base64.h\"" >> $OUT
echo >> $OUT
echo "namespace current {" >> $OUT
echo "namespace inl {" >> $OUT
echo >> $OUT
echo "// clang-format off" >> $OUT
echo -n "static const std::string bricks_system_current_inl = current::Base64Decode(\"" >> $OUT
base64 -w 0 current.inl >> $OUT
echo "\");" >> $OUT
echo "// clang-format on" >> $OUT
echo  >> $OUT
echo "}  // namespace current::inl" >> $OUT
echo "}  // namespace current" >> $OUT
echo  >> $OUT
echo "#endif  // BRICKS_SYSTEM_CURRENT_INL_H" >> $OUT
