# In `Makefile`, do nothing for `current_build.h`. Use `MakefileWithCurrentBuild` to have it created.

.PHONY: phony_current_build

include $(shell readlink "${PWD}/Makefile")Impl

phony_current_build:
