// This file is necessary, as an autogenerated schema header file is `#include`-d from the test.
// It could just `#include "../../../current.h"`, but the test `#include`-s the autogenerated schema
// from within a namespace, making things slightly more tricky. -- D.K.

#include <chrono>

#include "../../../TypeSystem/Evolution/type_evolution.h"
#include "../../../TypeSystem/optional.h"
#include "../../../TypeSystem/struct.h"
#include "../../../TypeSystem/variant.h"
