// Autogenerated TypeScript and C5T/Current JSON.
// hash: b528c6626c40443d

/* tslint:disable */

export type Primitives = {
  // It's the "order" of fields that matters.
  a: number;

  // Field descriptions can be set in any order.
  b: number;
  c: number;
  d: number;
  e: number;
  f: number;
  g: number;
  h: number;
  i: number;
  j: string;
  k: number;
  l: number;

  // Multiline
  // descriptions
  // can be used.
  m: boolean;
  n: number;
  o: number;
};

export type A = {
  a: number;
};

export type B = A & {
  b: number;
};

export type B2 = A;

export type Empty = {};

export type X = {
  x: number;
};

export type E = number;

export type Y = {
  e: E;
};

export type MyFreakingVariant = {
  A?: A;
  X?: X;
  Y?: Y;
};

export type C5TCurrentVariant_T9227782347108675041 = {
  A?: A;
  X?: X;
  Y?: Y;
};

export type C = {
  e: Empty;
  c: MyFreakingVariant;
  d: C5TCurrentVariant_T9227782347108675041;
};

export type C5TCurrentVariant_T9228482442669086788 = {
  A?: A;
  B?: B;
  B2?: B2;
  C?: C;
  Empty?: Empty;
};

export type Templated_T9209980946934124423 = {
  foo: number;
  bar: X;
};

export type Templated_T9227782344077896555 = {
  foo: number;
  bar: MyFreakingVariant;
};

export type TemplatedInheriting_T9200000002835747520 = A & {
  baz: string;
  meh: Empty;
};

export type Templated_T9209626390174323094 = {
  foo: number;
  bar: TemplatedInheriting_T9200000002835747520;
};

export type TemplatedInheriting_T9209980946934124423 = A & {
  baz: string;
  meh: X;
};

export type TemplatedInheriting_T9227782344077896555 = A & {
  baz: string;
  meh: MyFreakingVariant;
};

export type Templated_T9200000002835747520 = {
  foo: number;
  bar: Empty;
};

export type TemplatedInheriting_T9201673071807149456 = A & {
  baz: string;
  meh: Templated_T9200000002835747520;
};

export type TrickyEvolutionCases = {
  o1: string | null;
  o2: number | null;
  o3: string[] | null;
  o4: number[] | null;
  o5: A[] | null;
  o6: [string, A | null];
  o7: Record<string, A | null>;
};

export type FullTest = {
  // A structure with a lot of primitive types.
  primitives: Primitives;
  v1: string[];
  v2: Primitives[];
  p: [string, Primitives];
  o: Primitives | null;

  // Field | descriptions | FTW !
  q: C5TCurrentVariant_T9228482442669086788;
  w1: Templated_T9209980946934124423;
  w2: Templated_T9227782344077896555;
  w3: Templated_T9209626390174323094;
  w4: TemplatedInheriting_T9209980946934124423;
  w5: TemplatedInheriting_T9227782344077896555;
  w6: TemplatedInheriting_T9201673071807149456;
  tsc: TrickyEvolutionCases;
};
