name: "make cmake_test"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  cmake-run-tests-debug:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: make cmake_test
        run: make cmake_test
