name: cmake

on:
  workflow_dispatch:

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: run test
        run: |
          export TESTDIR="cmake_test_$(date +%s)"
          echo "Running in ${TESTDIR}"
          mkdir "${TESTDIR}"
          cp cmake/Makefile "${TESTDIR}/"
          cp cmake/CMakeLists.txt "${TESTDIR}/"
          cp cmake/run-cmake-test.sh "${TESTDIR}/"
          (cd "${TESTDIR}"; ./run-cmake-test.sh)
