name: cmake

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - stable

jobs:
  try-cmake:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: run test
        run: |
          export TESTDIR="cmake_test_$(date +%s)/deeply/nested/dir"
          echo "Running in ${TESTDIR}"
          mkdir -p "${TESTDIR}"
          cp cmake/Makefile "${TESTDIR}/"
          cp cmake/CMakeLists.txt "${TESTDIR}/"
          cp cmake/run-cmake-test.sh "${TESTDIR}/"
          (cd "${TESTDIR}"; ./run-cmake-test.sh)
